import { ADDRESS_FORM_FIELDS } from '../../common/address/address-form';

export const ADD_ADDRESS_FORM_INITIAL_VALUES = {
  [ADDRESS_FORM_FIELDS.RECIPIENT]: '',
  [ADDRESS_FORM_FIELDS.FIRST_LINE]: '',
  [ADDRESS_FORM_FIELDS.SECOND_LINE]: '',
  [ADDRESS_FORM_FIELDS.CITY]: '',
  [ADDRESS_FORM_FIELDS.STATE_PROVINCE_REGION]: '',
  [ADDRESS_FORM_FIELDS.POSTAL_CODE]: '',
  [ADDRESS_FORM_FIELDS.COUNTRY]: '',
};
