const ENVIRONMENT_OPTIONS = {
  DEV: 'dev',
  STAGING: 'staging',
};

const PLATFORM_OPTIONS = {
  IOS: 'ios',
  ANDROID: 'android',
};

const FIREBASE_CONFIG_FILENAME = {
  [PLATFORM_OPTIONS.IOS]: 'GoogleService-Info.plist',
  [PLATFORM_OPTIONS.ANDROID]: 'google-services.json',
};

const FIREBASE_CONFIG_SRC_PATH = {
  [ENVIRONMENT_OPTIONS.DEV]: {
    [PLATFORM_OPTIONS.IOS]: `environments/${ENVIRONMENT_OPTIONS.DEV}/${
      FIREBASE_CONFIG_FILENAME[PLATFORM_OPTIONS.IOS]
    }`,
    [PLATFORM_OPTIONS.ANDROID]: `environments/${ENVIRONMENT_OPTIONS.DEV}/${
      FIREBASE_CONFIG_FILENAME[PLATFORM_OPTIONS.ANDROID]
    }`,
  },
  [ENVIRONMENT_OPTIONS.STAGING]: {
    [PLATFORM_OPTIONS.IOS]: `environments/${ENVIRONMENT_OPTIONS.STAGING}/${
      FIREBASE_CONFIG_FILENAME[PLATFORM_OPTIONS.IOS]
    }`,
    [PLATFORM_OPTIONS.ANDROID]: `environments/${ENVIRONMENT_OPTIONS.STAGING}/${
      FIREBASE_CONFIG_FILENAME[PLATFORM_OPTIONS.ANDROID]
    }`,
  },
};

const FIREBASE_CONFIG_DESTINATION_PATH = {
  [PLATFORM_OPTIONS.IOS]: `${PLATFORM_OPTIONS.IOS}/${
    FIREBASE_CONFIG_FILENAME[PLATFORM_OPTIONS.IOS]
  }`,
  [PLATFORM_OPTIONS.ANDROID]: `${PLATFORM_OPTIONS.ANDROID}/app/${
    FIREBASE_CONFIG_FILENAME[PLATFORM_OPTIONS.ANDROID]
  }`,
};

module.exports = {
  PLATFORM_OPTIONS,
  FIREBASE_CONFIG_DESTINATION_PATH,
  FIREBASE_CONFIG_SRC_PATH,
};
