export const ROUTES_IDS = {
  PROTECTED_STACK: 'stack.protected',
  PUBLIC_STACK: 'stack.public',
  ONBOARDING_STACK: 'stack.onboarding',
  HOME_STACK: 'stack.home',
  LOGIN_SCREEN: 'screen.login',
  SIGN_UP_SCREEN: 'screen.signUp',
  LANDING_SCREEN: 'screen.landing',
  COMPLETE_PROFILE_SCREEN: 'screen.completeProfile',
  ONBOARDING_INSTRUCTIONS_SCREEN: 'screen.onboardingInstructions',
  ONBOARDING_QUESTIONS_SCREEN: 'screen.onboardingQuestions',
  ALLOW_NOTIFICATIONS_SCREEN: 'screen.allowNotifications',
  HOME_SCREEN: 'screen.home',
  SEARCH_SCREEN: 'screen.search',
  LIVE_MODAL: 'modal.live',
  TAB_NAVIGATOR: 'navigator.tab',
  HOME_TAB: 'tab.home',
  SCHEDULE_TAB: 'tab.schedule',
  HITS_TAB: 'tab.hits',
  BREAKERS_TAB: 'tab.breakers',
} as const;
