export const ROUTES_IDS = {
  PROTECTED_STACK: 'stack.protected',
  PUBLIC_STACK: 'stack.public',
  ONBOARDING_STACK: 'stack.onboarding',
  LOGIN_SCREEN: 'screen.login',
  SIGN_UP_SCREEN: 'screen.signUp',
  LANDING_SCREEN: 'screen.landing',
  COMPLETE_PROFILE_SCREEN: 'screen.completeProfile',
  INSTRUCTIONS_SCREEN: 'screen.instructions',
  ONBOARDING_QUESTIONS_SCREEN: 'screen.onboardingQuestions',
  ALLOW_NOTIFICATIONS_SCREEN: 'screen.allowNotifications',
  TAB_NAVIGATOR: 'navigator.tab',
  LIVE_TAB: 'tab.live',
  SCHEDULE_TAB: 'tab.schedule',
  HITS_TAB: 'tab.hits',
  BREAKERS_TAB: 'tab.breakers',
} as const;
